### ISSUE TITLE
Crash when Payload doesn't contains messages

### ISSUE THREAD

**Issue by UnTogoVi** [ushahidi/SMSSync#236] opened 2015-01-24 09:40 UTC
Hi,

There's a crash in
SMSSync/smssync/src/main/java/org/addhen/smssync/messages/ProcessMessage.java
line 143

when payload only contains "success" item.

echo '{ payload: { "success" : "true" , "task": "send" , "messages": [ { "to": "'.$from .'" , "message" : "thank you for your sms" } ] } }';

will work.

echo '{ payload: { "success" : "true" } }';

leads to smssync crash.

Tx

**Comment by eyedol** [comment] 2015-03-03 07:05
@UnTogoVi I really can't reproduce this on my device. Anyone experiencing this as well?

**Comment by eyedol** [comment] 2015-03-20 00:58
Closing. Feel free to re-open if it's still there in the next release.

**Closed by eyedol** 2015-03-20 00:58 UTC
