### ISSUE TITLE
sent_timestamp is not unix time format compliant

### ISSUE THREAD

**Issue by redbullpeter** [ushahidi/SMSSync#179] opened 2014-06-22 12:26 UTC
The sent_timestamp that is being sent is not in the correct unix time format.

For example the time returned today was: 1403438526000
If you convert this strictly, assuming 64 bit time stamp, then the date would be: 13/03/46443 11:00:00 GMT

The time stamp should actually be: 1403438526
Which converts to: 22/06/2014 12:02:06 GMT

Millisecond accuracy should be represented as 1403438526.000

**Comment by sorinpohontu** [comment] 2015-04-21 06:50
@eyedol I think you can close this issue for 2.8.0.

**Closed** 2015-04-21 07:22 UTC

**Comment by emerick-pro** [comment] 2018-03-18 17:52
Hello ! 
I am sorry to raise the issue when this was closed. I am having the issue of the timestamp from Android SMSSync that is always the same value (2147483647).  I am building the application using PHP 
```
 $sent_timestamp = (int) $_POST['sent_timestamp'];
 $event['event'] .='Bwarungitswe saa  : '.$sent_timestamp/1000;
```
And every time I am receiving the same value. 2147483647.  Can you please help to figure out the cause or the solution?
